"""add created_at to password_reset_tokens

Revision ID: 1c7ac1364f74
Revises: eacf011cc092
Create Date: 2025-10-10 02:58:14.592151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c7ac1364f74'
down_revision: Union[str, None] = 'eacf011cc092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'updated_at')
    op.drop_column('password_reset_tokens', 'created_at')
    # ### end Alembic commands ###
